### PR TITLE
fix entries with lowercase are never shown with limit 25

### PR DESCRIPTION
**Pull request by un1versal**
##Not For merging its untested, please dont be mad at me.

This is probably going to be 100% wrong, no idea what correct fix is.... but this is what I found in relation to the issue described in https://github.com/InuSasha/xbmc/commit/0681700bd5c437c3acb0a7e472acc0d20b2ce9af#commitcomment-14064119

The issue is the iZombie entry is being ignored because it starts with lower case **i**

Using the following query fixes this issue.

```SELECT * FROM tvshow_view  WHERE watchedCount != 0 AND totalCount != watchedCount ORDER BY LOWER(c00) LIMIT 25;```

@sopparus came up with the above query and it works on **mysql** and **sqlite**, I just wanted to show that the issue can be resolved by using ORDER BY LOWER(c00) so you can review and implement properly if you want.

I hope it helps and sorry for the noise.

### CODE REVIEW

**Comment by InuSasha** [comment]
It sounds ok, but i will decide the limit/no limit question first. 
(And actual a have a big problem on an other topic, nothing with xbmc. this will take many time :( )

**Comment by un1versal** [comment]
Yes, I think I understand, but changing default limit may not be a good way to fix this.

I hope you resolve your other issue, no rush.

**Comment by InuSasha** [comment]
i think the limit was added to recentlyadded, because this would fetch all movies/episodes. this will be a very huge list. But the inprogress should short (the 25+ of you, was it bit frighteningly for me)

**Comment by un1versal** [comment]
25 limit is enough for default even for me. The issue is lowercase is ignored. on this.

**Comment by InuSasha** [comment]
what about remove limit and order? this can be done by frontend.

**Comment by un1versal** [comment]
Limit is not the problem, like I said.

Ordering can be changed but it wont fix the lowercase being ignored and also breaks the A-Z ordering everyone is used to here.

**Comment by un1versal** [comment]
Ive tested this patch now, it has 0 effect on query. never mind,

**Comment by un1versal** [comment]
@InuSasha great thx it was merged finally.

the lowercase is still an issue with more than 25 in progress as its pushed to last

**Pull request closed without merging**
